### PR TITLE
Improved a bit display of results at the server

### PR DESCRIPTION
**Pull request by edugrasa**
Now it is possible to track down stats of multiple simultaneous clients looking at the servers logs

### CODE REVIEW

**Comment by dstaesse** [comment]
for now a very useful addition, but we should have a call on what people need from tgen in the near future for WP6 experiments and build a feature list...
can you clean the output a little bit more (and maybe justify the output to a certain number of characters, something like:
adding "(Port ID %lu)", change the line to:

```
LOG_INFO("Port ID %4d: %9llu SDUs (%llu bytes) in %12lu us => %8.4f p/s, %4.4f Mb/s",
```

and in the summary change it to:

```
LOG_INFO("Port-id (%4d) summary: %9llu SDUs, %9llu bytes in %9ld ms=> %4.4f Mb/s", 
port_id, sdus, bytes_read, ms, static_cast<float>((bytes_read * 8.0) / (ms * 1000)));
```

**Comment by dstaesse** [comment]
and install an ntp client on the build machine, your commits are in the future!

**Comment by msune** [comment]
He is a visionary ;)

**Comment by edugrasa** [comment]
Sorry, NTP client installed :P 
Agree we have to discuss new features, but I don't think this is a new feature, it is completing the work: the server already supports multiple simultaneous clients, if the port-id is not added to the log, there's no way to know from which client are the statistics.

**Comment by dstaesse** [comment]
further cleaned the output, obsoleted by PR #14.
I will now create a --csv option that will output CSV files at a specified location at the server per port_id.

**Pull request closed without merging**
