### PR TITLE
build: use boost.m4 to detect libboost libraries

### LINKED ISSUE #16: configure fails determining libboost-thread version
checking whether debug related features have been enabled... no
checking for boostlib >= 1.55... yes
checking whether the Boost::Thread library is available... yes
configure: error: Could not find a version of the library!

You have to execute it with --with-boost-libdir=/usr/lib/i386-linux-gnu/ in order to succeed

### PR DESCRIPTION
**Pull request by msune**
Use a more modern approach to detect boost libraries using boost.m4.
Remove old MACROs.

fixes #16 

@lbergesio could you please check this. **Make sure to do a make maintainer clean or an autoupdate**

### CODE REVIEW

**Comment by dstaesse** [comment]
@msune, great! I was going to look into this myself today.
I tried your build, but got errors:
./bootstrap and ./configure pass all checks, 
but then make gives me:

```
rina_tgen-server.o: In function `thread_data_base':
/usr/include/boost/thread/pthread/thread_data.hpp:144: undefined reference to `vtable for boost::detail::thread_data_base'
rina_tgen-server.o: In function `boost::thread::start_thread()':
/usr/include/boost/thread/detail/thread.hpp:180: undefined reference to `boost::thread::start_thread_noexcept()'
rina_tgen-server.o: In function `server::run()':
/users/dstaesse/traffic-generator/src/server.cc:72: undefined reference to `boost::thread::detach()'
rina_tgen-server.o: In function `~thread':
/usr/include/boost/thread/detail/thread.hpp:255: undefined reference to `boost::thread::detach()'
/usr/include/boost/thread/detail/thread.hpp:255: undefined reference to `boost::thread::detach()'
rina_tgen-server.o: In function `boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf1<void, server, int>, boost::_bi::list2<boost::_bi::value<server*>, boost::_bi::value<int> > > >::~thread_data()':
/usr/include/boost/thread/detail/thread.hpp:91: undefined reference to `boost::detail::thread_data_base::~thread_data_base()'
rina_tgen-server.o: In function `~thread_data':
/usr/include/boost/thread/detail/thread.hpp:91: undefined reference to `boost::detail::thread_data_base::~thread_data_base()'
rina_tgen-server.o: In function `boost::thread_exception::thread_exception(int, char const*)':
/usr/include/boost/thread/exceptions.hpp:51: undefined reference to `boost::system::system_category()'
rina_tgen-server.o: In function `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:222: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:223: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:224: undefined reference to `boost::system::system_category()'
rina_tgen-server.o:(.rodata._ZTIN5boost6detail11thread_dataINS_3_bi6bind_tIvNS_4_mfi3mf1Iv6serveriEENS2_5list2INS2_5valueIPS6_EENS9_IiEEEEEEEE[_ZTIN5boost6detail11thread_dataINS_3_bi6bind_tIvNS_4_mfi3mf1Iv6serveriEENS2_5list2INS2_5valueIPS6_EENS9_IiEEEEEEEE]+0x10): undefined reference to `typeinfo for boost::detail::thread_data_base'
collect2: error: ld returned 1 exit status
make[3]: *** [rina-tgen] Error 1
```

thoughts?

**Comment by msune** [comment]
Seems an issue with boost.m4 in some environtments when other boost libs require the thread library:

https://github.com/tsuna/boost.m4/issues/41

Can you try if removing `[mt]` from here:

https://github.com/msune/traffic-generator/blob/fix_build_boost/configure.ac#L101-L102

Works? Alternatively add to LDFLAGS= -lboost_threads, but that should not be the right solution and I doubt it would work without tricking libtool.

**Comment by dstaesse** [comment]
Neither seems to work on my side...

**Comment by msune** [comment]
First commit updated. That should fix the compilation issue. I did not realise that `BOOST_THREAD` was not adding the libs to `LDFLAGS`.

Added a commit to fix some warnings compiling C files, and removing `-Wextra` as per discussed.

Works for me (Debian 8). Please retry.

**Comment by dstaesse** [comment]
ACK

**Comment by dstaesse** [comment]
@lbergesio, can you ACK this as well?

**Comment by lbergesio** [comment]
No, I can not ack it because I have the library installed in a non-default location. I still need to specify it in the configura command but that is my problem.

**Comment by msune** [comment]
shall we merge?

**Pull request merged**
